import './global.css';
import { AppLayout } from './app-layout';
import { SolanaProvider } from './solana-provider';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by @solana-developers/preset-next@2.0.6',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SolanaProvider>
          <AppLayout>{children}</AppLayout>
        </SolanaProvider>
      </body>
    </html>
  );
}
