[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "3KCNCJuETwV6ALJXs3JpAmxLVXYGipQ4nYVYMaDXKRxG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"
